### ISSUE TITLE
J3.0 internal Joomla plugin config loses admin wrapper

### ISSUE THREAD

**Issue by tripslip38** [jfusion/org.jfusion.jfusion#1]
I'm using jFusion for Mediawiki integration in this case, so after building the package from the Joomla30 branch, and installing, I proceeded to configure Mediawiki. This worked fine. 

Then, I tried to configure the Joomla internal plugin for the master. This broke, as it somehow lost its status of being wrapped in the administrator panel. See screenshot.

Because of this, there are no buttons to proceed with configuring the plugin.

![Screen Shot 2013-04-05 at 2 40 07 PM](https://f.cloud.github.com/assets/3527183/346175/be2867dc-9e39-11e2-986f-016b6931af3e.png)

Would love to see more work on J3.0 branch. It is very important to me.

**Comment by fanno** [comment]
new branch is jfusion2.0
