### ISSUE TITLE
XSS security bug in phpbb3 plugin

### ISSUE THREAD

**Issue by georgwaechter** [jfusion/org.jfusion.jfusion#12]
Hey folks,

one of our website users brought up a XSS security flaw in our phpbb installation. After investigating the issue, we found out that jfusion is responsible for this bug. The issue is related to the postprocessing of the markup. 

At the moment, jfusion does same dangerous regex replacements, that allow to inject arbitrary javascript code. We found one place in the code, but there may be other lines with the same problem. It would be great if somebody more experienced with this code could have another look on it.

**Details**
The [line 318](https://github.com/jfusion/org.jfusion.jfusion/blob/release/components/com_jfusion/plugins/phpbb3/public.php#L318) in the parseBody function replaces all "#" hrefs in all anchors to the current url. If not escaping the url correctly, you can add more attributes to the <a tag, for instance imagine a url like http://test.com/?bad=" onmousemove=...

The fixed line could be:
`$replace_body[] = '"' .htmlspecialchars($data->fullURL) . '#$1"';`

Thanks and all the best

Georg

**Comment by fanno** [comment]
fixed: it "global"
https://github.com/jfusion/org.jfusion.jfusion/commit/1e5c2f1973430fae83742ab9e47599c59ac080db

can you verify it works for you as well ?

**Comment by georgwaechter** [comment]
Hi fanno,

thanks, yes we can confirm that this commit fixes the security flaw. A dangerours url that we got from our user does not inject any JS anymore.

all the best

Georg

**Comment by fanno** [comment]
is there any change you can email me a sample of the url so that i may learn from it pehaps ? you can change what ever you need to change.

-Thanks

**Comment by georgwaechter** [comment]
of course, i emailed it to you

**Comment by fanno** [comment]
Also can you edit the issue on github (its a "blueprint" ) for hackers to
know the "exploid" ?

i will do the same to my responces.

2015-05-07 13:52 GMT+02:00 Georg Wächter <notifications@github.com>:
