### ISSUE TITLE
model.jfusion.php fatal error

### ISSUE THREAD

**Issue by tripslip38** [jfusion/org.jfusion.jfusion#2]
Branch Joomla30

Since I'm trying to use this for Mediawiki frameless integration, I figured that despite not having the internal plugin working, I could at least make it load Mediawiki. I setup a menu item, and upon testing it, got an error. Here's the log entry from Apache error.log:
(identifying domain information X'ed out.)

`[error] [client XXX.XXX.XXX.XXX] PHP Fatal error:  Call to undefined method JRegistry::getValue() in /media/ebs1/www/xxx/xxx.net/administrator/components/com_jfusion/models/model.jfusion.php on line 855, referer: http://www.xxx.net/`

**Comment by fanno** [comment]
the new branch for joomla 3.x is jfusion2.0
