### ISSUE TITLE
After installing the extension got error

### ISSUE THREAD

**Issue by ronoliverclarin** [jfusion/org.jfusion.jfusion#4]
I receive this error once I am trying to logged in to my admin panel:

Fatal error: Call to undefined method JUser::authorize() in /home/ronolive/public_html/administrator/components/com_jfusion/models/model.jfusion.php on line 1128

what's happening?

I am using the JFusion Git version for Joomla 3

**Comment by mattybeez** [comment]
change the JUser::authorize to authorise ...typo i think

**Comment by ronoliverclarin** [comment]
Please give detailed instruction.

**Comment by fanno** [comment]
this is not a location i normally visit (only reason for the delay),

i would suggest you use out support platform if it is stable and code.jfusion.org if it is dev dev version

**Comment by fanno** [comment]
also joomla30 branc is removed we now working on jfusion2.0 i ad to start over.
